Refactor :: oauth middleware
gofr-dev/gofr pull request #1018
Opened 2024-09-12 03:33 UTC by srrathi

## Pull Request Template

**Description:**

Refactored oauth middleware  by breaking it into smaller functions for reducing it's cognitive complexity.
Solves #997 

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-09-12 06:00 UTC, vipul-rawat commented on pkg/gofr/http/middleware/oauth.go
> +		return errors.New("authorization header is required")
```suggestion
		return errors.New("Authorization header is required")
```

2024-09-12 06:02 UTC, ccoVeille commented on pkg/gofr/http/middleware/oauth.go
> +}
This 2 methods could be merged

2024-09-12 06:02 UTC, ccoVeille commented on pkg/gofr/http/middleware/oauth.go
> +	if len(headerParts) != 2 || headerParts[0] != "Bearer" {
I would use strings.CutPrefix(authHeader, "Bearer ") then check the found flag

2024-09-13 02:04 UTC, srrathi commented
@vipul-rawat @ccoVeille Thanks for the review. I have added the requested changes.

2024-09-14 16:13 UTC, ccoVeille approved these changes

2024-09-16 09:29 UTC, aryanmehrotra requested changes
@srrathi your tests are breaking in the local system as well. 
Probably something is wrong with the implementation, could you verify

2024-09-19 03:03 UTC, srrathi commented
> @srrathi your tests are breaking in the local system as well. Probably something is wrong with the implementation, could you verify

@aryanmehrotra Thanks for informing. These test cases are breaking
```
=== RUN   TestOAuthInvalidTokenFormat
    oauth_test.go:68: 
        	Error Trace:	/home/runner/work/gofr/gofr/pkg/gofr/http/middleware/oauth_test.go:68
        	Error:      	"authorization header format must be ***" does not contain "Authorization header format must be ***"
        	Test:       	TestOAuthInvalidTokenFormat
--- FAIL: TestOAuthInvalidTokenFormat (0.00s)
=== RUN   TestOAuthEmptyAuthHeader
    oauth_test.go:92: 
        	Error Trace:	/home/runner/work/gofr/gofr/pkg/gofr/http/middleware/oauth_test.go:92
        	Error:      	"authorization header is required\n" does not contain "Authorization header is required"
        	Test:       	TestOAuthEmptyAuthHeader
--- FAIL: TestOAuthEmptyAuthHeader (0.01s)
```

**Reason** - because I changed the error message being started from a capital letter as it is causing linting error and golang error messages should start from lower case letter. I have changed the same in the test cases as well so it should fix it.

2024-09-19 10:41 UTC, aryanmehrotra commented
@srrathi pipeline is still failing could you please look into it.

2024-09-20 03:32 UTC, srrathi commented
> @srrathi pipeline is still failing could you please look into it.

@aryanmehrotra This is what failing the pipeline, no idea why but will check in the weekend.

```
=== RUN   Test_SQLRetryConnectionInfoLog
could not connect with 'user' user to 'test' database at 'host:3201', error: dial tcp: lookup host on 127.0.0.53:53: server misbehaving
    sql.go:200: Unexpected call to *sql.MockMetrics.SetGauge([app_sql_open_connections 1]) at /home/runner/work/gofr/gofr/pkg/gofr/datasource/sql/sql.go:200 because: 
        expected call at /home/runner/work/gofr/gofr/pkg/gofr/datasource/sql/sql_test.go:275 doesn't match the argument at index 1.
        Got: 1 (float64)
        Want: is equal to 0 (float64)
        expected call at /home/runner/work/gofr/gofr/pkg/gofr/datasource/sql/sql_test.go:276 doesn't match the argument at index 0.
        Got: app_sql_open_connections (string)
        Want: is equal to app_sql_inUse_connections (string)
    controller.go:98: missing call(s) to *sql.MockMetrics.SetGauge(is equal to app_sql_open_connections (string), is equal to 0 (float64)) /home/runner/work/gofr/gofr/pkg/gofr/datasource/sql/sql_test.go:275
    controller.go:98: missing call(s) to *sql.MockMetrics.SetGauge(is equal to app_sql_inUse_connections (string), is equal to 0 (float64)) /home/runner/work/gofr/gofr/pkg/gofr/datasource/sql/sql_test.go:276
    controller.go:98: aborting test due to missing call(s)
--- FAIL: Test_SQLRetryConnectionInfoLog (0.12s)
FAIL
coverage: 3.4% of statements in gofr.dev/pkg/...
FAIL	gofr.dev/pkg/gofr/datasource/sql	0.249s

```

2024-09-20 07:45 UTC, vipul-rawat approved these changes

2024-09-20 07:54 UTC, aryanmehrotra approved these changes

2024-09-20 07:54 UTC, merged