Supporting Migrations in Cassandra
gofr-dev/gofr pull request #1035
Opened 2024-09-19 09:51 UTC by coolwednesday

**Description:**

-   Closes #766 
-  Cassandra does not support transactions and even the batch function only allow DML commands. Hence we are not supporting transactions in Cassandra in Migrations. If the user might need atomicity in their DML queries, they can use the batch queries while writing their migrations file.

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

2024-09-20 06:55 UTC, Umang01-hash requested changes

2024-09-20 06:55 UTC, Umang01-hash commented on pkg/gofr/migration/cassandra.go
> +	CheckAndCreateCassandraMigrationTable = `CREATE TABLE IF NOT EXISTS gofr_migrations (
Can we keep this constant unexported as it is not being used outside the package?

2024-09-20 06:55 UTC, Umang01-hash commented on pkg/gofr/migration/cassandra.go
> +version bigint,
Please reformat this query into two lines instead of keeping each field into separate line.

2024-09-20 06:55 UTC, Umang01-hash commented on pkg/gofr/migration/cassandra.go
> +	c.Debugf("Cassandra last migration fetched value is: %v", lastMigration)
The log message should start with `lower-case`

2024-09-20 06:55 UTC, Umang01-hash commented on pkg/gofr/migration/cassandra.go
> +	c.Debug("Cassandra Migrator begin successfully")
Please start the log message with `lower-case`

2024-09-20 06:55 UTC, Umang01-hash commented on pkg/gofr/migration/cassandra_test.go
> +	ch := cassandraDS{Cassandra: mockCassandra}
Can we have a better naming for variable `ch` here?

2024-09-20 06:55 UTC, Umang01-hash commented on pkg/gofr/migration/cassandra_test.go
> +	mg, mockCassandra, mockContainer := cassandraSetup(t)
What does `mg` stands for ? Is it an acronym for **migrator** ? If yes we can just use the name `migrator`

2024-09-20 06:55 UTC, Umang01-hash commented on pkg/gofr/migration/clickhouse_test.go
> +	mg := ch.apply(&ds)
Please user another variable name apart from `mg` that should be more clearer

2024-09-20 07:42 UTC, Umang01-hash submitted a review, later dismissed

2024-09-23 09:54 UTC, aryanmehrotra approved these changes

2024-09-23 10:34 UTC, merged