Fixing Improper-sqlite-logs
gofr-dev/gofr pull request #1057
Opened 2024-09-27 06:49 UTC by coolwednesday

Closes #968 

<img width="661" alt="Screenshot 2024-09-27 at 12 13 53 PM" src="https://github.com/user-attachments/assets/2536b7f9-22b5-48b3-9c84-6e26e301a8ae">

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-09-27 07:12 UTC, Umang01-hash requested changes

2024-09-27 07:12 UTC, Umang01-hash commented on pkg/gofr/datasource/sql/sql_test.go
> +		if test.err == nil {
Instead of having an `if-else` statement in test , it's better to break down it into two test methods one for error case and one for success case

2024-09-27 07:12 UTC, Umang01-hash commented on examples/http-server/configs/.env
> +TRACE_EXPORTER=gofr
Why have we added this change here?

2024-09-27 07:24 UTC, Umang01-hash submitted a review, later dismissed

2024-09-27 09:31 UTC, vipul-rawat reviewed
Can we do this with the pretty print interface and using log struct, is that a feisable solution?
@aryanmehrotra

2024-09-30 06:58 UTC, vipul-rawat approved these changes

2024-09-30 07:48 UTC, aryanmehrotra approved these changes

2024-09-30 07:49 UTC, Umang01-hash approved these changes

2024-09-30 07:49 UTC, merged