Fix: Missing Connection Successful Logs
gofr-dev/gofr pull request #1206
Opened 2024-11-15 09:33 UTC by coolwednesday

## Pull Request Template

**Description:**

-   Closes #1204 

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-11-15 20:07 UTC, ccoVeille commented
Why closing?

2024-11-15 20:42 UTC, ccoVeille commented
Is it because this one superseded it?

https://github.com/gofr-dev/gofr/pull/1205

2024-11-16 14:25 UTC, coolwednesday commented
> Why closing?

There are continuous build fails. I will address that and then reopen, this PR.

2024-11-18 06:49 UTC, Umang01-hash commented on pkg/gofr/datasource/file/s3/fs.go
> +	f.logger.Infof("Connected to S3 bucket %s", f.config.BucketName)
here also we should start with a small case character

2024-11-18 06:50 UTC, Umang01-hash commented on pkg/gofr/datasource/file/ftp/fs.go
> +	f.logger.Infof("Connecting to FTP server at '%v'", ftpServer)
We should start with a small-case character for logging here just like we did for other datasources

2024-11-18 06:50 UTC, Umang01-hash commented on pkg/gofr/datasource/file/ftp/fs.go
> +	f.logger.Infof("Connected to FTP server at '%v'", ftpServer)
Log should be started with a small case character here also

2024-11-18 08:27 UTC, ccoVeille commented on pkg/gofr/datasource/kv-store/badger/mock_logger.go
> +//Code generated by MockGen. DO NOT EDIT.
```suggestion
// Code generated by MockGen. DO NOT EDIT.
```

2024-11-18 08:27 UTC, ccoVeille commented on pkg/gofr/datasource/pubsub/kafka/mock_interfaces.go
> +//Code generated by MockGen. DO NOT EDIT.
I don't get how this change was introduced

Do you have a new version of mockgen?

2024-11-18 08:27 UTC, ccoVeille commented on pkg/gofr/datasource/pubsub/nats/client.go
> +	c.logger.Log("connecting to NATS sever at %v", c.Config.Server)
```suggestion
	c.logger.Log("connecting to NATS server at %v", c.Config.Server)
```

😁

2024-11-18 09:48 UTC, Umang01-hash approved these changes

2024-11-20 09:16 UTC, ccoVeille commented on pkg/gofr/datasource/cassandra/cassandra.go
> +	c.logger.Debugf("connecting to cassandra at %v on port %v to keyspace %v", c.config.Hosts, c.config.Port, c.config.Keyspace)
```suggestion
	c.logger.Debugf("connecting to Cassandra at %v on port %v to keyspace %v", c.config.Hosts, c.config.Port, c.config.Keyspace)
```

2024-11-20 09:16 UTC, ccoVeille commented on pkg/gofr/datasource/cassandra/cassandra_test.go
> +	mockLogger.EXPECT().Debugf("connecting to cassandra at %v on port %v to keyspace %v", "host1", 9042, "test_keyspace")
```suggestion
	mockLogger.EXPECT().Debugf("connecting to Cassandra at %v on port %v to keyspace %v", "host1", 9042, "test_keyspace")
```

Maybe everywhere in fact

2024-11-20 09:16 UTC, ccoVeille commented on pkg/gofr/datasource/clickhouse/clickhouse.go
> +	c.logger.Debugf("connecting to clickhouse db at %v to database %v", c.config.Hosts, c.config.Database)
```suggestion
	c.logger.Debugf("connecting to ClickHouse db at %v to database %v", c.config.Hosts, c.config.Database)
```

2024-11-20 09:16 UTC, ccoVeille commented on pkg/gofr/datasource/file/ftp/mock_interface.go
> +//Code generated by MockGen. DO NOT EDIT.
Nope

2024-11-20 09:16 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +	c.logger.Debug(fmt.Sprintf("connecting to mongoDB at %v to database %v", c.config.URI, c.config.Database))
```suggestion
	c.logger.Debugf("connecting to mongoDB at %v to database %v", c.config.URI, c.config.Database)
```

2024-11-20 09:16 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +	c.logger.Debug(fmt.Sprintf("connecting to mongoDB at %v to database %v", c.config.URI, c.config.Database))
```suggestion
	c.logger.Debug(fmt.Sprintf("connecting to MongoDB at %v to database %v", c.config.URI, c.config.Database))
```

2024-11-21 06:56 UTC, Umang01-hash requested changes
I think to maintain code uniformity isn't it better to introduce `Debugf` in interface wherever needed instead of using **Debug(fmt.Sprintf())** ?

2024-11-21 06:56 UTC, Umang01-hash commented on pkg/gofr/datasource/pubsub/nats/client.go
> +	c.logger.Debugf("connecting to NATS server at %v", c.Config.Server)
This log is a repeated in the Connect method called here:

```go
connManager := NewConnectionManager(c.Config, c.logger, c.natsConnector, c.jetStreamCreator)
	if err := connManager.Connect(); err != nil {
		c.logger.Errorf("failed to connect to NATS server at %v: %v", c.Config.Server, err)
		return err
	}
```


And inside the Connect method we also have this log:



```go
// Connect establishes a connection to NATS and sets up JetStream.
func (cm *ConnectionManager) Connect() error {
	cm.logger.Debugf("Connecting to NATS server at %v", cm.config.Server)

	opts := []nats.Option{nats.Name("GoFr NATS JetStreamClient")}

	if cm.config.CredsFile != "" {
		opts = append(opts, nats.UserCredentials(cm.config.CredsFile))
	}

	connInterface, err := cm.natsConnector.Connect(cm.config.Server, opts...)
	if err != nil {
		cm.logger.Errorf("failed to connect to NATS server at %v: %v", cm.config.Server, err)

		return err
	}
```

We need to remove either of them

2024-11-21 07:58 UTC, Umang01-hash approved these changes

2024-11-22 09:59 UTC, vipul-rawat approved these changes

2024-11-24 03:44 UTC, vikash commented
If we have introduced debugf, we should check if we still need debug there. If not, we should probably remove it. @coolwednesday

2024-11-27 05:54 UTC, Umang01-hash approved these changes

2024-11-27 06:39 UTC, vipul-rawat approved these changes

2024-11-27 06:39 UTC, merged