Fix: Correcting time unit for logs of added http-service
gofr-dev/gofr pull request #1214
Opened 2024-11-18 05:15 UTC by coolwednesday

## Pull Request Template

**Description:**
-   Closes #1197 

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-11-18 08:37 UTC, ccoVeille commented
Please update the PR description

```diff
-we use to display as microseconds, which is wrong. Hence corrected the calculations to be done in Microseconds.
+we use to display as milliseconds, which is wrong. Hence corrected the calculations to be done in microseconds.
```

2024-11-20 11:47 UTC, ccoVeille approved these changes

2024-11-20 11:52 UTC, ccoVeille commented
> > Please update the PR description
> > 
> > ```diff
> > -we use to display as microseconds, which is wrong. Hence corrected the calculations to be done in Microseconds.
> > +we use to display as milliseconds, which is wrong. Hence corrected the calculations to be done in microseconds.
> > ```
> 
> @ccoVeille , I mean what I wrote. The log displays 8 microseconds where in actually gofr calculates it as 8 milliseconds. So we are correcting that, to corrrectly show ....8,000 µs.

OK, so I think I'm lost.

Let's reboot.

Your text says:

>  we use to display as microseconds, which is wrong. Hence corrected the calculations to be done in microseconds.

So it means
- it was in **microseconds**
- we fixed to use **microseconds**

The code :
- was calling **milliseconds**
- is updated to call **microseconds**

So for me, there is a problem with the text. The code is fine

2024-11-21 08:05 UTC, aryanmehrotra requested changes
Missing changes for transaction in SQL DB and openTSDB

2024-11-27 07:26 UTC, aryanmehrotra approved these changes

2024-11-27 07:27 UTC, merged