Fixing Linters and tests in file-stores (ftp, sftp, s3)
gofr-dev/gofr pull request #1262
Opened 2024-12-03 06:38 UTC by coolwednesday

-   prequisite to closing #964
-   Some methods previously included required a running container for validation. These methods have been temporarily removed and, if needed, their mocking will be addressed separately in a future PRs.

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-12-04 07:00 UTC, Umang01-hash submitted a review, later dismissed

2024-12-04 07:23 UTC, ccoVeille commented on pkg/gofr/datasource/file/ftp/fs.go
> +	appFtpStats   = "app_ftp_stats"
```suggestion
	appFTPStats   = "app_ftp_stats"
```

It's an acronym, fixing an unexported constant won't cause problem

2024-12-04 07:23 UTC, ccoVeille commented on pkg/gofr/datasource/file/ftp/fs_test.go
> +	errMockErr  = errors.New("mocked error")
```suggestion
	errMockSentinel  = errors.New("mocked error")
```

Or anything but "error mock error"

2024-12-04 07:23 UTC, ccoVeille commented on pkg/gofr/datasource/file/s3/file.go
>  type s3file struct {
```suggestion
type s3File struct {
```

2024-12-04 07:23 UTC, ccoVeille commented on pkg/gofr/datasource/file/s3/file_parse.go
> +//   - The FileInfo interface is used to describe file system objects, and IsDir is one of its methods
```suggestion
//   - The [FileInfo] interface is used to describe file system objects, and IsDir is one of its methods
```

2024-12-04 07:23 UTC, ccoVeille commented on pkg/gofr/datasource/file/s3/fs.go
> +	conn    s3conn
You define conn, then use s3conn

Maybe you could rename conn to s3Client or s3ClientConn

2024-12-04 07:23 UTC, ccoVeille commented on pkg/gofr/datasource/file/s3/fs_dir.go
> +		}
strings.CutPrefix could help

2024-12-04 07:23 UTC, ccoVeille commented on pkg/gofr/datasource/file/s3/fs_dir.go
> +		if name[0] == '0' {
A comment would be appreciated

2024-12-04 07:23 UTC, ccoVeille commented on pkg/gofr/datasource/file/s3/fs_dir.go
> +		size:         *res.Contents[0].Size,
These access to *res.Contents[0] everywhere in this method, causes me to wonder about panic.

Maybe you could store into a variable, then use only the variable

2024-12-04 07:23 UTC, ccoVeille commented on pkg/gofr/datasource/file/s3/interface.go
> +type s3conn interface {
Can you rename it? Thanks


```suggestion
type s3Conn interface {
```

2024-12-04 10:00 UTC, ccoVeille commented on pkg/gofr/datasource/file/s3/fs.go
> +	conn    s3conn
Yes, anything that not increase the confusion like having s3conn and conn being different things

2024-12-05 12:27 UTC, aryanmehrotra requested changes
Lets create 3 different PRs.

2024-12-05 12:27 UTC, aryanmehrotra commented on pkg/gofr/datasource/file/ftp/fs.go
> +	f.metrics.NewHistogram(appFTPStats, "Response time of File System operations in milliseconds.", ftpBuckets...)
time should be in microseconds as we are exporting time in microseconds

2024-12-05 12:33 UTC, aryanmehrotra requested changes
Lets create 3 different PRs.

2024-12-05 12:33 UTC, aryanmehrotra commented on pkg/gofr/datasource/file/s3/fs.go
> +	TypeFile      = "file"
why exported?

2024-12-05 13:13 UTC, aryanmehrotra commented
Closing as separated PRs are being created.

2024-12-05 13:13 UTC, closed without merging

2024-12-05 13:42 UTC, ccoVeille commented
Split to

- #1265
-