Updated createAndSendRequest to add headers
gofr-dev/gofr pull request #1277
Opened 2024-12-09 05:23 UTC by ssshekhu53

- Added check for if the `Content-type` header is not set, then `application/json` will be set by default.
- Updated the test as well

2024-12-09 06:37 UTC, coolwednesday approved these changes

2024-12-09 06:40 UTC, Umang01-hash approved these changes

2024-12-09 06:58 UTC, aryanmehrotra requested changes

2024-12-09 06:58 UTC, aryanmehrotra commented on pkg/gofr/service/new_test.go
> +		[]byte("{Test Body}"), map[string]string{"header1": "value1", "content-type": "application/json"})
test needs to be updated with the following cases - 
1. We have added content-type but we are not verifying if the server which received the request received it with the content-type and the correct value.
2. We should be also adding a case where content-type is not set by the user and it automatically gets set.
3. Content-type is set with application/xml or something and it is not overrided.

2024-12-10 06:29 UTC, aryanmehrotra approved these changes

2024-12-10 06:32 UTC, merged