Fix: Disconnected Spans exported for Remote-log-url
gofr-dev/gofr pull request #1280
Opened 2024-12-09 10:34 UTC by coolwednesday

## Pull Request Template

**Description:**

- Closes #1278 
- Previously disconnected spans were created for each fetch request of the remote log .....
- The change in code makes sure that the all the traces exported for one http-request has spans in hierarchy.
- It also makes sure that we don't export retry connection logs for sql connection, as it is not a developer concern. Logs will be suffice in such case.

<img width="1042" alt="Screenshot 2024-12-09 at 1 46 45 PM" src="https://github.com/user-attachments/assets/659449cb-2760-4c93-b5ce-7ea3427e9333">

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-12-10 06:08 UTC, Umang01-hash requested changes

2024-12-10 06:08 UTC, Umang01-hash commented on pkg/gofr/exporter.go
> +		if s.Name() == "sql.connector.connect" {
can we use a constant here instead of this hard-coded string?

2024-12-10 06:08 UTC, Umang01-hash commented on pkg/gofr/service/new.go
> +	// Create the HTTP request with the tracing context
Here and everywhere we have added new comments, we should make sure that they end with a period (.)

2024-12-10 08:06 UTC, Umang01-hash approved these changes

2024-12-13 07:47 UTC, aryanmehrotra approved these changes

2024-12-13 07:47 UTC, Umang01-hash approved these changes

2024-12-13 08:35 UTC, merged