Fix : Incorrect MongoDB Connection Logs
gofr-dev/gofr pull request #1355
Opened 2024-12-31 05:00 UTC by coolwednesday

- Closes #1326 
- Replacing uri in logs with Host for mongo
- Description : As uri ,also has password and username .... it should not be present in the logs....hence replaced it with host config.

2024-12-31 05:15 UTC, Umang01-hash submitted a review, later dismissed

2024-12-31 09:13 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +	return host
Regexp are evil, and also they are slow

Here you are parsing something that look a like an URI

I mean it's `scheme://user:pass@host:port/path`

Can't you use net/url package ? 

https://pkg.go.dev/net/url#ParseRequestURI

Then Hostname https://pkg.go.dev/net/url#URL.Hostname

2025-01-02 08:43 UTC, Umang01-hash submitted a review, later dismissed

2025-01-03 06:34 UTC, aryanmehrotra requested changes

2025-01-03 06:34 UTC, aryanmehrotra commented on pkg/gofr/datasource/mongo/mongo.go
> +	c.logger.Debugf("connecting to MongoDB at %v to database %v", c.config.Host, c.config.Database)
we are first logging it and then we are checking the host and later based on uri or host we are printing log, which might print and empty host

2025-01-04 10:21 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +		config.User, config.Password, config.Host, config.Port, config.Database)
Be careful here

This approach could lead to bugs

user and password (but more likely the password can contain character that needs to be escaped, such as @#: it would lead to invalid URL, or password that won't be readable by mongodb client

They should be escaped I'm unsure what is the RFC for this.

Also the database may contains slash or ? (I'm usure it's possible with mongoDB), so here url.PathEscape should be used for  comfig.Database

I would like to suggest creating a url.URL with all required fields then use the .String

Please note, this could be done in a separate PR as the parttern of forging URL by concatenation might be used somewhere else

2025-01-07 08:36 UTC, ccoVeille approved these changes

2025-01-07 08:36 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +		Host:   fmt.Sprintf("%s:%d", config.Host, config.Port),
there is https://pkg.go.dev/net#JoinHostPort for this

it could lead to issue with IPv6 otherwise

2025-01-08 05:51 UTC, Umang01-hash submitted a review, later dismissed

2025-01-08 06:24 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo_test.go
> +				Password: "password",
Could you please update the password to something that cont wins characters that need to be encoded

Something like


```suggestion
				Password: "p@##word:",
```


This way you will validate they are escaped

2025-01-08 06:24 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo_test.go
> +				Password: "password",
Could you add a test without authentication

I mean with user and password being empty

The code supports it

2025-01-08 06:24 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +	case config.Database == "":
Shouldn't you prevent (error) or warn (log)

URI and host, port, database, username and port cannot be used together.

I'm a bit afraid someone will use the URI, then will provide user and password.

Another way to consider this is to populate url.URL from the ParseURI instead of creating a URL object, then to set the field if present in the config

2025-01-08 06:24 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +	parsedURL, err := url.Parse(uri)
https://pkg.go.dev/net/url#ParseRequestURI would be safer

2025-01-08 06:37 UTC, coolwednesday commented on pkg/gofr/datasource/mongo/mongo.go
> +	case config.Database == "":
That is the reason I am checking if URI is present or not ....
If it is ...host name is extracted for logs and that uri is only used for connection....

If it is not ..it checks for the other fields of the config to create the uri itself ... What is the issue here ? I am not able to understand ....

2025-01-08 06:52 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo_test.go
> +			expectedErr: "parse \"\": empty url",
The change you add to do here because of my suggestion make me think this error should be wrapped

See https://github.com/gofr-dev/gofr/pull/1355#discussion_r1906560707

2025-01-08 06:52 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +		return "", err
```suggestion
		return "", fmt.Errorf("%w: %w", errParseHost, err)
```
See https://github.com/gofr-dev/gofr/pull/1355#discussion_r1906559791

2025-01-08 06:58 UTC, coolwednesday commented on pkg/gofr/datasource/mongo/mongo.go
> +		return "", err
I don't feel the same, 
If the url is empty....empty url error is already wrapped around `"error generating Mongo URI"`, errParseHost error seems irrelevant in that context.

2025-01-08 06:59 UTC, coolwednesday commented on pkg/gofr/datasource/mongo/mongo_test.go
> +			expectedErr: "parse \"\": empty url",
See [#1355 comment](https://github.com/gofr-dev/gofr/pull/1355#discussion_r1906567159)

2025-01-08 07:04 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +		return "", err
Indeed

2025-01-08 07:04 UTC, ccoVeille approved these changes

2025-01-08 07:09 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +	}
Could this happen now we use ParseRequestURI ?

Is errParseHost still needed?

2025-01-08 07:29 UTC, coolwednesday commented on pkg/gofr/datasource/mongo/mongo.go
> +	}
In one of the test cases, you see, it can be for this use case,

`mongodb://username:password@:27017/database?authSource=admin`

2025-01-08 07:37 UTC, ccoVeille commented on pkg/gofr/datasource/mongo/mongo.go
> +	}
Indeed. Thanks for checking

2025-01-08 11:25 UTC, Umang01-hash approved these changes

2025-01-08 12:53 UTC, aryanmehrotra approved these changes

2025-01-08 12:53 UTC, merged

2026-10-12 16:16 UTC, BranchSun requested changes
## Code Review 摘要

Nice direction: replacing the credential-bearing URI with the host in logs addresses the reported leak, and the new `generateMongoURI`/`getDBHost` helpers with table-driven tests are a good step towards testable config handling. However, the new URI validation is too strict and changes behaviour: `getDBHost` rejects `mongodb+srv://` (Atlas) and multi-host replica-set URIs, so `Connect()` now aborts before connecting for configurations that previously worked, and credentials are double-escaped via `url.QueryEscape`/`url.PathEscape` inside `url.UserPassword`/`url.URL.Path`, which breaks passwords containing special characters. Please also switch the new `Debugf` to the parsed `host` value, otherwise the log stays empty for URI-based configs. Good instinct to add unit tests for the new helpers — adding `mongodb+srv` and multi-host cases would have caught the regression.

**决策（policy）**: REQUEST_CHANGES

### 发现问题
- 🟠 high: 1
- 🟡 medium: 1
- 🟢 low: 1

2026-10-12 16:16 UTC, BranchSun commented on pkg/gofr/datasource/mongo/mongo.go
> +	}
🟠 **bug** (high)

`getDBHost` rejects every URI whose scheme is not exactly `mongodb`, and `generateMongoURI` turns that into a hard failure, so `Connect()` now logs `error generating mongo URI: incorrect URI for mongo` and returns without connecting. The supported `mongodb+srv://` scheme used by MongoDB Atlas is rejected here, even though the driver handles it and the old code passed the URI straight to `options.Client().ApplyURI`. The same happens for multi-host replica-set URIs (e.g. `mongodb://u:p@h1:27017,h2:27017/db`): `url.Parse` fails on the second port with `invalid port`, and `generateMongoURI` propagates that error, so a previously working connection string now aborts before any connection attempt. This is a regression for existing users, not just a logging change.

**建议**: Accept both supported schemes and avoid making host extraction fatal. For example: `switch parsedURL.Scheme { case "mongodb", "mongodb+srv": default: return "", errIncorrectURI }`, and for the multi-host case either parse the first host manually or make host extraction best-effort — return the raw URI for logging (or a placeholder) with a warning instead of failing `Connect()` when only the derived log host cannot be parsed. Please also add a test case covering a `mongodb+srv://` URI and a multi-host URI.

**证据**: `	if parsedURL.Scheme != "mongodb" {`

2026-10-12 16:16 UTC, BranchSun commented on pkg/gofr/datasource/mongo/mongo.go
> +
🟡 **bug** (medium)

Credentials are escaped twice. `url.UserPassword` already percent-encodes its arguments when `url.URL.String()` is called, so pre-escaping with `url.QueryEscape` produces wrong credentials: a password `p@ss` becomes `p%40ss` here and then `p%2540ss` in the final URI, which the driver decodes back to `p%40ss`. `QueryEscape` also encodes a space as `+`, and `+` is a literal character in userinfo, so a password containing a space is sent unchanged as `+` rather than a space. Any credential containing characters outside `[A-Za-z0-9-_.~]` (e.g. `@`, `#`, `$`, space, `%`) will silently fail authentication. The same double escaping applies to the database name on the line above (`Path: "/" + url.PathEscape(config.Database)` is escaped again by `u.String()`).

**建议**: Pass the raw values and let `net/url` do the escaping once: `u.User = url.UserPassword(config.User, config.Password)` and `Path: "/" + config.Database`. A unit test with a password containing a special character would catch this.

**证据**: `		u.User = url.UserPassword(url.QueryEscape(config.User), url.QueryEscape(config.Password))`

2026-10-12 16:16 UTC, BranchSun commented on pkg/gofr/datasource/mongo/mongo.go
>  	}
🟢 **bug** (low)

This log line uses `c.config.Host` instead of the `host` value returned by `generateMongoURI`, while all the other log lines in this function use `host`. When the client is configured through `Config.URI` (the deprecated path, where `Host` is empty), the debug message prints an empty host (`connecting to MongoDB at  to database X`) — exactly the case this PR is trying to make readable.

**建议**: Use the parsed value: `c.logger.Debugf("connecting to MongoDB at %v to database %v", host, c.config.Database)`, consistent with the `Ping` and success logs below.

**证据**: `	c.logger.Debugf("connecting to MongoDB at %v to database %v", c.config.Host, c.config.Database)`