[EN] Add tests for config, requests
gofr-dev/gofr pull request #207
Opened 2024-01-11 03:11 UTC by srijan-27

- Fixed tests for cmd/request and config
- Added tests for http/request

2024-01-11 11:26 UTC, aryanmehrotra requested changes

2024-01-11 11:26 UTC, aryanmehrotra commented on pkg/gofr/cmd/request_test.go
> +		{"test", "true"},
case can also be added about behaviour when we have keys with special characters and empty keys, same for values as well.

2024-01-11 11:26 UTC, aryanmehrotra commented on pkg/gofr/config/godotenv_test.go
> +		configs = "TEST=test\nNAME=gofr\nKEY_123=value123"
same can be tested here about special characters and different possible keys and values

2024-01-30 10:36 UTC, srijan-27 commented
Deleting this for now.

2024-01-30 10:36 UTC, closed without merging