Add support for sqlite3
gofr-dev/gofr pull request #445
Opened 2024-04-08 08:04 UTC by rokerzfirst101

**Description:**
- Added `sqlite3` as an acceptable value for `DB_DIALECT`
- Add import for `github.com/mattn/go-sqlite3` driver
- Updated the logic to initialize the connection string using only`DB_HOST` for sqlite

**How it works:**

To use SQLite as the Database, the user would need to provide the following configs or environment variables:
```env
DB_DIALECT=sqlite3
DB_HOST={connection-string}
```

Connection String Ref: https://github.com/mattn/go-sqlite3?tab=readme-ov-file#connection-string

Closes #423

2024-04-08 10:01 UTC, Umang01-hash commented
@rokerzfirst101 Can you please also update the Test function `TestSQL_getDBConnectionString`and add the test case for newly added code.

2024-04-08 10:11 UTC, rokerzfirst101 commented
sure

2024-04-10 06:52 UTC, vipul-rawat commented
@rokerzfirst101 - please add/extend documentation for using Sqlite in gofr - https://gofr.dev/docs/advanced-guide/dealing-with-datasources

2024-04-10 09:11 UTC, rokerzfirst101 commented
@vipul-rawat I've updated the database documentation

2024-04-10 19:31 UTC, vikash commented
Adding a requirement for cgo reduces compatibility. Many people do prefer to use go without cgo. There is an implementation which does not require cgo, we should prefer that.

2024-04-10 19:32 UTC, vikash requested changes
Adding a requirement for cgo reduces compatibility. Many people do prefer to use go without cgo. There is an implementation which does not require cgo, we should prefer that

2024-04-10 21:31 UTC, rokerzfirst101 commented on pkg/gofr/migration/sql.go
> -
this statement will not work when there are multiple databases with the `gofr_migrations` table

2024-04-10 22:22 UTC, rokerzfirst101 commented
I've replaced the `github.com/mattn/go-sqlite3` pkg with `modernc.org/sqlite`

2024-05-06 09:47 UTC, aryanmehrotra commented
@rokerzfirst101 Rather than taking connection string from the user, we can take the configs in the following way and it keep consistent across for all SQL databases which we currently support
```
DB_HOST=localhost #Not possible to add? does it support connecting to a remote file in that case it can be supported
DB_USER=root # can be used
DB_PASSWORD=password # can be used
DB_NAME=test #db_name?
DB_DIALECT=mysql #sqlite will be used here
```

2024-05-23 09:51 UTC, closed without merging

2024-05-23 09:51 UTC, rokerzfirst101 commented
closing as stale, will add another one