Added Masking of PII data in logs
gofr-dev/gofr pull request #465
Opened 2024-04-15 18:01 UTC by SuyeshBadge

## Pull Request Template
Added feature to mask PII data into logs.

**Description:**

- This PR introduces a new feature to mask Personally Identifiable Information (PII) fields in log entries. The `DefaultFilter` in the `logging` package has been updated to support masking of various PII fields, such as name, email, phone number, Social Security number, credit card number, date of birth, biometric data, and IP address.
- The motivation behind this change is to enhance data privacy and security by preventing sensitive user information from being logged in plaintext.
- This feature will benefit users by ensuring compliance with privacy regulations and reducing the risk of data breaches or unauthorized access to sensitive information.

**Breaking Changes (if applicable):**

- There are no breaking changes introduced by this PR.

**Additional Information:**

- The changes rely on the built-in `reflect` package in Go for inspecting and modifying struct fields.
- [ISSUE] https://github.com/gofr-dev/gofr/issues/459
- New test cases have been added to ensure comprehensive testing of the PII masking functionality.

**Checklist:**

- [x] I have formatted my code using `goimport` and `golangci-lint`.
- [x] All new code is covered by unit tests.
- [x] This PR does not decrease the overall code coverage.
- [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-04-15 19:08 UTC, SuyeshBadge commented
@aryanmehrotra, @vipul-rawat, and @Umang01-hash,

I'm initiating a discussion thread to commence the implementation of the mentioned feature. Let's delve into the various potential changes and methodologies to effectively incorporate this feature.

Looking forward to your valuable insights and contributions.

2024-04-16 10:25 UTC, vipul-rawat reviewed
Please check the linters, pipeline is failing.

Also is there a way to not use reflect, if possible?

You might also need to look for a way for users to the masking fields at the time of application creation! Or if masking is required at all!

2024-04-16 10:25 UTC, vipul-rawat commented on pkg/gofr/logging/logger.go
> +		filter = args[0].(Filter)
This would panic if the args provided do not implement `Filter` interface.
We can do a boolean(ok) check instead.

2024-04-16 10:25 UTC, vipul-rawat commented on pkg/gofr/logging/logger.go
> +		filter = args[0].(Filter)
This would panic if the args provided do not implement `Filter` interface.
We can do a boolean(ok) check instead.

2024-04-16 10:25 UTC, vipul-rawat commented on pkg/gofr/logging/logger_test.go
> +		// Add more test cases as needed
Empty comment

2024-04-16 10:25 UTC, vipul-rawat commented on pkg/gofr/logging/logger.go
> +func contains(slice []string, str string) bool {
naming convention could be better for `slice`, not informative of the usage

2024-04-18 18:46 UTC, SuyeshBadge commented
Hey @vipul-rawat, I've pushed the requested changes along with the formatting and linting fixes. Please have a look once you get a chance and let me know if anything is missing.

2024-04-21 09:18 UTC, vipul-rawat requested changes
There are still 2 things - 
1. Can you add an example on how enabling and disabling the filtered logging would look from user's perspective
2. I am still not sure if this would handle the pointers

2024-04-21 18:33 UTC, SuyeshBadge commented
Certainly, @vipul-rawat will make the changes and update you accordingly.

2024-04-21 18:45 UTC, SuyeshBadge commented
> I am still not sure if this would handle the pointers

You're right to be concerned about handling pointers. The current implementation assumes that the fields are direct values and not pointers. Will update this too.

2024-04-29 19:32 UTC, SuyeshBadge commented
Hey @vipul-rawat ,
I've updated the filtered logging feature to support pointer values and added documentation on how to use it. However, one test check is failing, and I'm not sure why.
Could you please take a look and provide some guidance on fixing it?
Thanks for your help!

2024-05-02 05:05 UTC, vipul-rawat commented
@SuyeshBadge This implementation requires users to be aware of the logger and define it themselves, whereas for most use cases the framework is responsible for managing the logger itself. Can we use configs reading to achieve the same instead of the user defining the filter in the main file?

Also, how can a user-defined filter be called `DefaultFilter`? Should be CustomFilter or equivalent.

The pipeline was failing due to an MQTT test! Probably the public server was experiencing some downtime. Rerunning should fix the same. Also, update the local with development.

2024-05-05 20:41 UTC, SuyeshBadge commented
Hello @vipul-rawat,

Could you kindly provide further clarification regarding the utilization of configuration readings in this context? Specifically, would you prefer me to:

1. Pass the configuration explicitly to the `NewLogger` function?
2. Expose a `setConfig` method that will be invoked prior to declaring the logger?
3. Directly invoke `godotenv` from the `logger.go` file?

I require additional details to proceed effectively. Thank you.

2024-05-06 10:35 UTC, vipul-rawat commented
@SuyeshBadge What I mean is that currently according to your implementation, the NewLogger is being made by the user in main, but what we want is that the filter gets configured automatically during the app creation (during `gofr.New()`), so for example if user gives the config `MASKED_FIELDS=<comma separated field names>` then what framework does is that it adds the filter with those names, we don't want to have the filtering of fields by default. 

I think something like `SetFilter` similar to `setConfig` that is suggested in point 2 seems good.

> Point 1 will not be viable as it would be a breaking change and not worth it.
> Point 3 also not viable as logger's responsibility is not to read configurations or load them.

@srijan-27 FYA

2024-05-06 20:21 UTC, SuyeshBadge commented
Hey @vipul-rawat,

I've implemented the changes as per your instructions. Additionally, I addressed several linting issues that were present. Kindly review the updates at your convenience. With the latest implementation, the application now reads values from the configuration and configures the logger accordingly. Furthermore, I've revised the documentation for improved clarity and understanding.

2024-05-06 20:28 UTC, SuyeshBadge commented
Also if possible could you please re-run the checks, some of them are failing.

2024-05-07 10:15 UTC, srijan-27 requested changes

2024-05-07 10:15 UTC, srijan-27 commented on docs/advanced-guide/filtered-logging/page.md
> +- `LOGGER_MASKING_FIELDS`: A comma-separated list of field names that should be masked in log messages.
@SuyeshBadge - This use-case can be fulfilled with a single config, not required to create a bool config as well. Please fix this.

2024-05-07 10:15 UTC, srijan-27 commented on docs/advanced-guide/filtered-logging/page.md
> +    logger := logging.NewLogger(logging.INFO)
it is not required to create a new logger. We can use `app.Logger()`

2024-05-07 10:15 UTC, srijan-27 commented on pkg/gofr/container/container.go
> +	c.createPubSub(conf)
This should not be included in this PR, as it is not directly related to masking logs. Please create a separate PR for this.

2024-05-07 10:15 UTC, srijan-27 commented on pkg/gofr/container/container.go
> -	// Populating an instance of app_info with the app details, the value is set as 1 to depict the no. of instances
deleting the comments is not required. Please revert

2024-05-15 10:00 UTC, srijan-27 commented
@SuyeshBadge - Are you still working on this?

2024-05-15 10:02 UTC, SuyeshBadge commented
> @SuyeshBadge - Are you still working on this?

Yes @srijan-27 will update soon

2024-05-17 19:53 UTC, SuyeshBadge commented
Hey @srijan-27 and @vipul-rawat,

The changes we discussed have been implemented. Please review them and let me know if anything else is needed.

Thanks!

2024-05-20 10:03 UTC, srijan-27 requested changes
@SuyeshBadge - please take a look

2024-05-20 10:03 UTC, srijan-27 commented on pkg/gofr/logging/logger_test.go
> +
unwanted extra newline, it can be removed.

2024-05-20 10:03 UTC, srijan-27 commented on pkg/gofr/logging/logger_test.go
> +	}
same as above, assert.Equal can be used.

2024-05-25 14:06 UTC, SuyeshBadge commented
Hey @srijan-27 @vipul-rawat,

I see there have been some recent changes pushed on the PR. Is there anything pending on my end? If yes, please let me know. Otherwise, let's move forward with this.

Thanks!

2024-06-06 10:22 UTC, srijan-27 commented
@SuyeshBadge - Have you tested these changes by running an example on local and verifying whether the fields of struct are getting masked?

2024-06-06 11:09 UTC, SuyeshBadge commented
Not yet @srijan-27 .

2024-06-10 11:52 UTC, aryanmehrotra commented
@SuyeshBadge can we connect and close this ASAP?
If you are stuck we can work together!

2024-06-10 16:30 UTC, srijan-27 commented
> Certainly, @aryanmehrotra .
> 
> I identified the issue with the filter not working and have implemented a fix. However, we can still connect if you'd like to discuss the changes in detail.

@SuyeshBadge - If you have implemented the fix, please push the code and we can verify then.

2024-06-11 06:58 UTC, SuyeshBadge commented
Sure folks, will push it today.

2024-06-11 19:21 UTC, SuyeshBadge commented
Hey Folks, Pushed some latest changes please take a look and let me know if this works. 

FYI @srijan-27 @aryanmehrotra

2024-06-12 07:04 UTC, srijan-27 commented
@SuyeshBadge - can you please attach the snapshots for the masked logs, if you have tested it locally on any example.

2024-06-12 15:14 UTC, SuyeshBadge commented
Sure, @srijan-27. Attached are the snapshots of the logs, the code, and the keys that need to be masked.

- **Snapshot of fields that need to be masked**  
  ![fields to be masked](https://github.com/gofr-dev/gofr/assets/59205766/f7d39630-b716-47a4-896d-93118bde02fe)

- **Snapshot of the log after masking**  
  ![log of masking](https://github.com/gofr-dev/gofr/assets/59205766/607b455c-b8dd-48b6-b148-819bee5e8943)

- **Snapshot of logs without masking**  
  ![logs without masking](https://github.com/gofr-dev/gofr/assets/59205766/bd0828e4-c466-4df0-82af-41664847cdc2)

- **Snapshot of the code snippet**  
  ![code for masking](https://github.com/gofr-dev/gofr/assets/59205766/7abb8871-503b-42ab-8254-177fe26d47dd)

2024-06-12 15:17 UTC, SuyeshBadge commented
Sure, @srijan-27. Attached are the snapshots of the logs, the code, and the keys that need to be masked.

- **Snapshot of fields that need to be masked**  
  ![fields to be masked](https://github.com/gofr-dev/gofr/assets/59205766/f7d39630-b716-47a4-896d-93118bde02fe)

- **Snapshot of the log after masking**  
  ![log of masking](https://github.com/gofr-dev/gofr/assets/59205766/607b455c-b8dd-48b6-b148-819bee5e8943)

- **Snapshot of logs without masking**  
  ![logs without masking](https://github.com/gofr-dev/gofr/assets/59205766/bd0828e4-c466-4df0-82af-41664847cdc2)

- **Snapshot of the code snippet**  
  ![code for masking](https://github.com/gofr-dev/gofr/assets/59205766/7abb8871-503b-42ab-8254-177fe26d47dd)

- **Snapshot of the log, if the data passed, is a pointer**
![code](https://github.com/gofr-dev/gofr/assets/59205766/eb60f6ab-de15-4b06-a106-1754cb2498c9)

![Pointer](https://github.com/gofr-dev/gofr/assets/59205766/a64cdcd8-e83c-4daa-b975-829d2eae8f55)

2024-06-12 15:56 UTC, srijan-27 commented
@SuyeshBadge - have you tried passing the struct as args in log?

Something like this:
```go
func helloHandler(ctx *gofr.Context) (interface{}, error) {
	user := struct {
		Name     string
		Email    string
		Password string
	}{
		"srijan", "srijan.rastogi@gofr.dev", "secret-123",
	}

	ctx.Logger.Infof("%v", user)

	return "hello world!", nil
}
```

2024-06-12 16:18 UTC, SuyeshBadge commented
Hey @srijan-27,
In this case, the output will not be masked because the message being passed to the filter method is a string that is formatted before being passed. I'm not entirely sure if this is the intended behavior. Let me know what you think and what we can do here.

2024-06-13 07:40 UTC, srijan-27 commented
@SuyeshBadge - I don't think this should be intended behaviour. As if we consider this, then we are restricting user to only mask fields in unformatted logs. We should have a behaviour such that user can mask fields irrespective of the log formatting.

2024-06-13 14:55 UTC, SuyeshBadge commented
Hey @srijan-27, Can we discuss this over a call? Let me know if you are available.

2024-06-19 04:56 UTC, SuyeshBadge commented
Hi @srijan-27,

The issue is fixed. We are now masking the arguments, ensuring that all types of data passed are masked and not limited to any specific case. If you encounter any more edge cases, please feel free to raise them.

Also, let me know if this solution works for you. I am attaching a snapshot of the updated use cases.

---
**Snapshots**
![Struct example](https://github.com/gofr-dev/gofr/assets/59205766/4708d92e-0164-40aa-8402-a34426db39db)
![terminal](https://github.com/gofr-dev/gofr/assets/59205766/96262829-ecd8-4584-8890-6a19fb604606)

2024-06-20 06:48 UTC, srijan-27 commented
@SuyeshBadge - Although this implementation is masking the fields as required. But it is also adding a log which is not helpful and not understandable for user. See below:
<img width="1358" alt="Screenshot 2024-06-20 at 12 15 11 PM" src="https://github.com/gofr-dev/gofr/assets/44723623/bc2d9c1d-7ea0-4b04-830f-1f4ab092dcf7">

Also, the request/response log is missing in the new implementation:
<img width="621" alt="Screenshot 2024-06-20 at 12 15 40 PM" src="https://github.com/gofr-dev/gofr/assets/44723623/3e9c7780-820e-4554-b29d-99c1b058808d">

Please check this.

2024-06-21 03:24 UTC, SuyeshBadge commented
> @SuyeshBadge - Although this implementation is masking the fields as required. But it is also adding a log which is not helpful and not understandable for user. See below: <img alt="Screenshot 2024-06-20 at 12 15 11 PM" width="1358" src="https://private-user-images.githubusercontent.com/44723623/341301382-bc2d9c1d-7ea0-4b04-830f-1f4ab092dcf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDA0ODgsIm5iZiI6MTcxODk0MDE4OCwicGF0aCI6Ii80NDcyMzYyMy8zNDEzMDEzODItYmMyZDljMWQtN2VhMC00YjA0LTgzMGYtMWY0YWIwOTJkY2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAzMjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNzI2MDQyMzA3MzhjOTI2MzUzYjA2NDRjZDFkYzc1MDdiYjcxMmRlZTYxYTU5ODBhZDM5MDNlZWE3Yjk0NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6zzhU27U0ewfpg36ZIJFBJnR2KcMJvRKiNMGGB_xZ14">
> 
> Also, the request/response log is missing in the new implementation: <img alt="Screenshot 2024-06-20 at 12 15 40 PM" width="621" src="https://private-user-images.githubusercontent.com/44723623/341301961-3e9c7780-820e-4554-b29d-99c1b058808d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDA0ODgsIm5iZiI6MTcxODk0MDE4OCwicGF0aCI6Ii80NDcyMzYyMy8zNDEzMDE5NjEtM2U5Yzc3ODAtODIwZS00NTU0LWIyOWQtOTljMWIwNTg4MDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAzMjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MjYwMWY2MDhlNGQxODNjMDAxY2E3ZGI5ZjdmMzBlOWY2OGEzM2QwZjk3ZDEzNGU3OGRmZTFlOTNiODBmMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._mbfUyfJirsxe6tbTc5I_QNgWFqL0VYnpzW3m_biEnA">
> 
> Please check this.

Ohh Let me check why this log is being added here.

2024-07-01 10:20 UTC, srijan-27 commented
Spent time on fixing this implementation, but seems like a lot of issues with the current implementation like: not proper masking, breaking on existing logs. And also since this is using reflections a lot, so the performance is affected considerably. 
Hence, closing this PR. Would need to think of a better solution.
JFYI: @vipul-rawat, @aryanmehrotra, @Umang01-hash

2024-07-01 10:20 UTC, closed without merging

2024-08-03 21:28 UTC, srinivas365 commented
@srijan-27
I have created a package to redact the pii data. Can I implement this in gofr?
https://github.com/srinivas365/piishield/tree/v1.0.0

2024-08-05 03:40 UTC, srijan-27 commented
@srinivas365 - Sure, you can work on this issue: #459.
Please drop a comment there so I can assign this to you.