refactor initTracer method to integrate with Gofr tracer
gofr-dev/gofr pull request #481
Opened 2024-04-16 12:08 UTC by Umang01-hash

## Pull Request Template

**Description:**

- This PR intends to add support for gofr's custom trace exporter as well as collector.

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-04-17 07:17 UTC, aryanmehrotra requested changes

2024-04-17 07:17 UTC, aryanmehrotra commented on pkg/gofr/custom_exporter.go
> +type CustomExporter struct {
Can be changed to Exporter.

2024-04-17 07:17 UTC, aryanmehrotra commented on pkg/gofr/custom_exporter_test.go
> +		//	{"Empty Spans Slice", []sdktrace.ReadOnlySpan{}},
Test case shouldn't be commented

2024-04-17 07:17 UTC, aryanmehrotra commented on pkg/gofr/custom_exporter.go
> +func NewCustomExporter(endpoint string, logger logging.Logger) *CustomExporter {
GoDoc comments are missing.

2024-04-19 06:09 UTC, srijan-27 submitted a review, later dismissed

2024-04-19 06:10 UTC, aryanmehrotra submitted a review, later dismissed

2024-04-19 09:44 UTC, merged