Move mock_logger from testutil to logger
gofr-dev/gofr pull request #582
Opened 2024-05-08 11:59 UTC by srijan-27

## Pull Request Template

**Description:**

-   Provide a concise explanation of the changes made.
-   Mention the issue number(s) this PR addresses (if applicable).
-   Highlight the motivation behind the changes and the expected benefits.

**Breaking Changes (if applicable):**

-   List any breaking changes introduced by this PR.
-   Explain the rationale behind these changes and how they will impact users.

**Additional Information:**

-   Mention any relevant dependencies or external libraries used.
-   Include screenshots or code snippets (if necessary) to clarify the changes.

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-05-08 16:33 UTC, vikash commented
I think it does not really solve the problem. For example, now there are different log levels in mocklogger and the logger.

2024-05-08 16:36 UTC, vikash requested changes
Shifting the mockLogger to a sub package does not really change anything. Log level for examples are not the same.

2024-05-10 12:04 UTC, aryanmehrotra requested changes
We can see separately if we even want to use MockLogger, as NewLogger should also be good to use!

2024-05-10 12:29 UTC, aryanmehrotra approved these changes

2024-05-10 12:59 UTC, Umang01-hash approved these changes

2024-05-10 18:50 UTC, vikash approved these changes

2024-05-10 19:07 UTC, merged