add check for internal server to do error log
gofr-dev/gofr pull request #625
Opened 2024-05-16 05:52 UTC by vipul-rawat

## Pull Request Template

**Description:**

Error log for 5xx responses from server.

**Additional Information:**
Fixes issue #614 
![image](https://github.com/gofr-dev/gofr/assets/44166352/536fc096-5a5d-4742-8418-f08082cc3250)

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-05-16 06:10 UTC, srijan-27 approved these changes

2024-05-16 07:45 UTC, Umang01-hash approved these changes

2024-05-16 07:52 UTC, aryanmehrotra requested changes
As per issue ticket `Additionally, for JSON logging, the log should contain the error message`

In JSON format error message is not coming.

2024-05-17 10:41 UTC, aryanmehrotra approved these changes

2024-05-17 10:41 UTC, Umang01-hash approved these changes

2024-05-17 10:41 UTC, merged