Options to set table name and API path for REST handlers.
gofr-dev/gofr pull request #648
Opened 2024-05-24 06:31 UTC by illenko

**Description:**

-   Options to configure db table name and REST API path in `AddRESTHandlers`.

Usage example:
```go
type transactionEntity struct {
	ID       uuid.UUID `json:"id"`
	Datetime time.Time `json:"datetime"`
	Amount   float64   `json:"amount"`
	Category string    `json:"category"`
	Country  string    `json:"country"`
}

func (t *transactionEntity) TableName() string {
	return "transaction"
}

func (t *transactionEntity) RestPath() string {
	return "transactions"
}
```

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

2024-05-27 07:28 UTC, aryanmehrotra requested changes

2024-05-27 07:28 UTC, aryanmehrotra commented on pkg/gofr/crud_handlers.go
> +
can we update the names of the interface it is not right, you can refer go docs

https://go.dev/doc/effective_go#interface-names

2024-05-27 17:55 UTC, aryanmehrotra approved these changes

2024-05-28 06:43 UTC, srijan-27 approved these changes

2024-05-28 09:10 UTC, vipul-rawat approved these changes

2024-05-28 09:10 UTC, merged