Add apphealth in health response
gofr-dev/gofr pull request #706
Opened 2024-06-11 08:10 UTC by srijan-27

- Added `appHealth` details (appName, appVersion, status) in response of `.well-known/health` endpoint.
- Closes: #672

2024-06-11 08:30 UTC, aryanmehrotra submitted a review, later dismissed

2024-06-12 05:25 UTC, aryanmehrotra requested changes

2024-06-12 05:25 UTC, aryanmehrotra commented on pkg/gofr/container/health.go
> +	healthMap["status"] = "UP"
We should also handle, if any of the services is down status should be DEGRADED.

2024-06-12 07:13 UTC, aryanmehrotra approved these changes

2024-06-12 09:53 UTC, vipul-rawat approved these changes

2024-06-12 09:53 UTC, merged