update gofr version | fix replace command
gofr-dev/gofr pull request #869
Opened 2024-07-23 10:58 UTC by srijan-27

2024-07-23 11:04 UTC, Sianao commented
The other example without a go.mod and go.sum

2024-07-23 11:24 UTC, srijan-27 commented
> The other example without a go.mod and go.sum

@Sianao - Yes, I am working to add go.mod for all examples.

2024-07-23 11:47 UTC, Sianao commented
> > The other example without a go.mod and go.sum
> 
> @Sianao - Yes, I am working to add go.mod for all examples.

But if you add it , when new version release , we should update all example ?

2024-08-01 10:30 UTC, Umang01-hash requested changes

2024-08-01 10:30 UTC, Umang01-hash commented on .github/workflows/go.yml
> +          config: .ls-lint.yml
Can we revert this change. Seems unwanted..

2024-08-01 10:35 UTC, Umang01-hash approved these changes

2024-08-03 04:48 UTC, vipul-rawat approved these changes

2024-08-03 04:48 UTC, merged