fix panic and logic for validtion in basic auth
gofr-dev/gofr pull request #921
Opened 2024-08-09 06:38 UTC by Umang01-hash

## Pull Request Template

**Description:**

-   Resolves issue #918 
-   Resolves issue #917 

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

2024-08-09 10:03 UTC, ccoVeille requested changes

2024-08-09 10:07 UTC, Umang01-hash commented on pkg/gofr/gofr.go
>  // An error is logged if an odd number of arguments is provided.
Sure corrected.

2024-08-09 10:08 UTC, Umang01-hash commented on pkg/gofr/http/middleware/basic_auth.go
>  func validateCredentials(provider BasicAuthProvider, credentials []string) bool {
Got it will refactor and improve

2024-08-09 10:21 UTC, Umang01-hash commented on pkg/gofr/gofr.go
>  func (a *App) EnableBasicAuth(credentials ...string) {
Sure will use strings.Cut instead

2024-08-09 11:45 UTC, ccoVeille approved these changes
Thanks 👍

2024-08-09 11:46 UTC, ccoVeille commented on pkg/gofr/gofr.go
>  func (a *App) EnableBasicAuth(credentials ...string) {
Thanks. I think you will agree the code you wrote is way easier to read and test

2024-08-12 06:03 UTC, vipul-rawat approved these changes

2024-08-12 06:04 UTC, merged